/**
 * Hand-written Typert Host manifest for the rea-dsh bundle.
 *
 * Official packages ship this file generated by `@deepseek-ai/dsh-typert-generator`
 * from a TypeScript FaceModel. This bundle is pure JavaScript with no build step, so
 * the manifest is authored by hand against the same contract
 * (`@deepseek-ai/dsh-typert-loader`'s `validateTypertManifest` and
 * `@deepseek-ai/dsh-typert-registry`'s `validateInvocation`).
 *
 * The single invocation below exposes the Host's authoritative view of this row's
 * configuration to its own Client half. The Client half uses it in two ways:
 *
 *   1. as the read-only configuration source when `configForms` is unavailable
 *      (a composition without the settings UI), replacing a hard-coded default
 *      snapshot with the values the Host actually holds;
 *   2. as the reactive dependency its `ctx.inject` gate waits on, which is what
 *      lets the row's settings entry survive a 停用→启用 cycle
 *      (deepseek-harness#8452: a client half's `apply` does not re-run).
 *
 * @module @jedeiah/rea-dsh/typert
 */

/** A strict codec whose parser accepts any value; result codecs are not executed. */
function passthroughCodec() {
  return { parse: (value) => value };
}

/** Endpoint ids are spelled `<package>#<namespace>/<method>`, like the generated ones. */
const PACKAGE = '@jedeiah/rea-dsh';

/** The Host manifest consumed by the Typert loader on the row that mounts this bundle. */
export const TYPERT = {
  package: PACKAGE,
  face: 'host',
  schemas: [],
  invocations: [
    {
      id: `${PACKAGE}#reaAgents/introspect`,
      service: 'reaAgents',
      namespace: 'reaAgents',
      method: 'introspect',
      invocation: { kind: 'direct' },
      parameters: [],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: `${PACKAGE}#ReaAgentsConfig`,
        create: passthroughCodec,
      },
    },
  ],
  model: {
    services: [],
    events: [],
    objects: [],
  },
};

export default TYPERT;
