/**
 * Hand-written Typert Host manifest for the Session Purge bundle.
 *
 * Official packages ship this file generated by `@deepseek-ai/dsh-typert-generator`
 * from a TypeScript FaceModel. This bundle is pure JavaScript with no build step,
 * so the manifest is authored by hand against the same contract
 * (`@deepseek-ai/dsh-typert-loader`'s `validateTypertManifest` and
 * `@deepseek-ai/dsh-typert-registry`'s `validateInvocation`). What those two
 * require of an invocation is fixed and small:
 *
 *   - `id`, `service`, `namespace`, `method` strings; `namespace`/`method` must be
 *     RPC endpoint segments (`[A-Za-z0-9_$.-]+`, not `.`/`..`),
 *   - `invocation` receiver `{ kind: 'direct' }` (or a Context receiver, unused here),
 *   - one parameter record per wire field, each `{ name, wire, source: 'json' }`
 *     (a `lookup` parameter would name a registered Host object instead) and a
 *     strict codec,
 *   - a strict result codec.
 *
 * A strict codec is `{ mode: 'strict', typeSymbol, create() }` where `create()`
 * returns a schema object the Gateway decodes with (`schema.parse(value)`). The
 * Gateway never asks for more than `parse` on input and the optional
 * `encode`/`decode` on output, so no Zod runtime is needed on this face. Zod
 * *would* be the generated form; hand-rolling the two trivially-shaped schemas
 * keeps the bundle dependency-free and byte-identical on every machine.
 *
 * @module @jedeiah/session-purge/typert
 */

/**
 * A strict codec whose parser accepts any value it is given.
 * Used for results, which the Gateway forwards without validation.
 * @returns the codec.
 */
function passthroughCodec() {
  return { parse: (value) => value };
}

/**
 * A strict codec for one session id: a non-empty, path-safe string.
 * @returns the codec.
 */
function sessionIdCodec() {
  return {
    parse(value) {
      if (typeof value !== 'string' || value.length === 0 || value.length > 200 || /[/\\\0]/.test(value)) {
        throw new Error('session-purge: sessionId must be a non-empty path-safe string');
      }
      return value;
    },
  };
}

/** Endpoint ids, spelled `<package>#<namespace>/<method>` like the generated ones. */
const PACKAGE = '@jedeiah/session-purge';

/** The Host manifest consumed by the Typert loader on the row that mounts this bundle. */
export const TYPERT = {
  package: PACKAGE,
  face: 'host',
  schemas: [],
  invocations: [
    {
      id: `${PACKAGE}#sessionPurge/inspect`,
      service: 'sessionPurge',
      namespace: 'sessionPurge',
      method: 'inspect',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'sessionId',
          wire: 'sessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: `${PACKAGE}#SessionId`,
            create: sessionIdCodec,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: `${PACKAGE}#SessionPurgeInspection`,
        create: passthroughCodec,
      },
    },
    {
      id: `${PACKAGE}#sessionPurge/purge`,
      service: 'sessionPurge',
      namespace: 'sessionPurge',
      method: 'purge',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'sessionId',
          wire: 'sessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: `${PACKAGE}#SessionId`,
            create: sessionIdCodec,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: `${PACKAGE}#SessionPurgeReport`,
        create: passthroughCodec,
      },
    },
  ],
  model: {
    services: [],
    events: [],
    objects: [],
  },
};

export default TYPERT;
